import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import { usersService } from '@/services/user.service'
import { GetServerSideProps } from 'next'

const Home = ({ data }: { data: any[] }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          {data?.map((item, index) => {
            return (
              <a href="https://nextjs.org/docs" className={styles.card} key={index}>
                <h2>{item.name}</h2>
                <p>{item.email}</p>
              </a>
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} layout="fixed" />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async () => {
  const { data } = await usersService.getUser()

  return {
    props: {
      data,
    },
  }
}
